/* MST Engine - Taiwan Market Pulse Static Database */
/* Generated by build-stock-list.py v3.7.4 at 2026-09-05T22:42:56+08:00 */
/* Runtime is 100% static: no TWSE/TAIFEX API call is required by the website. */
const MARKET_DATA = Object.freeze({"taiex":{"history":[{"date":"2026/09/03","close":45857.66},{"date":"2026/09/04","close":46551.13}],"latest":{"date":"2026/09/04","close":46551.13}},"tx":{"date":"2026/09/04","contract":"TX","contractMonth":"202609","close":46704.0,"change":885.0,"changePct":1.93,"session":"一般"}});
const MARKET_DATABASE_META = Object.freeze({"builderVersion":"3.7.4","generatedAt":"2026-09-05T22:42:56+08:00","taiexRows":2,"taiexLatestDate":"2026/09/04","txDate":"2026/09/04","txContractMonth":"202609","sources":{"TAIEX":"https://openapi.twse.com.tw/v1/indicesReport/MI_5MINS_HIST + TWSE FMTQIK ALWAYS-CROSS-CHECK","TX":"https://openapi.taifex.com.tw/v1/DailyMarketReportFut + https://www.taifex.com.tw/cht/3/futDailyMarketExcel?commodity_id=TX ALWAYS-CROSS-CHECK"},"note":"Static same-day Market Pulse database. Runtime website makes no direct TWSE/TAIFEX API calls."});
function getMarketPulseData(){ return MARKET_DATA; }
