/* MST Engine - Taiwan Market Pulse Static Database */
/* Generated by build-stock-list.py v3.7.4 at 2026-08-12T01:36:42+08:00 */
/* Runtime is 100% static: no TWSE/TAIFEX API call is required by the website. */
const MARKET_DATA = Object.freeze({"taiex":{"history":[{"date":"2026/08/10","close":44928.76},{"date":"2026/08/11","close":45120.72}],"latest":{"date":"2026/08/11","close":45120.72}},"tx":{"date":"2026/08/11","contract":"TX","contractMonth":"202608","close":45090.0,"change":100.0,"changePct":0.22,"session":"Regular / TAIFEX Web"}});
const MARKET_DATABASE_META = Object.freeze({"builderVersion":"3.7.4","generatedAt":"2026-08-12T01:36:42+08:00","taiexRows":2,"taiexLatestDate":"2026/08/11","txDate":"2026/08/11","txContractMonth":"202608","sources":{"TAIEX":"https://openapi.twse.com.tw/v1/indicesReport/MI_5MINS_HIST + TWSE FMTQIK ALWAYS-CROSS-CHECK","TX":"https://openapi.taifex.com.tw/v1/DailyMarketReportFut + https://www.taifex.com.tw/cht/3/futDailyMarketExcel?commodity_id=TX ALWAYS-CROSS-CHECK"},"note":"Static same-day Market Pulse database. Runtime website makes no direct TWSE/TAIFEX API calls."});
function getMarketPulseData(){ return MARKET_DATA; }
