/* MST Engine - Taiwan Market Pulse Static Database */
/* Generated by build-stock-list.py v3.7.4 at 2026-08-30T15:08:36+08:00 */
/* Runtime is 100% static: no TWSE/TAIFEX API call is required by the website. */
const MARKET_DATA = Object.freeze({"taiex":{"history":[{"date":"2026/08/27","close":45975.22},{"date":"2026/08/28","close":46331.45}],"latest":{"date":"2026/08/28","close":46331.45}},"tx":{"date":"2026/08/28","contract":"TX","contractMonth":"202609","close":46357.0,"change":293.0,"changePct":0.64,"session":"一般"}});
const MARKET_DATABASE_META = Object.freeze({"builderVersion":"3.7.4","generatedAt":"2026-08-30T15:08:36+08:00","taiexRows":2,"taiexLatestDate":"2026/08/28","txDate":"2026/08/28","txContractMonth":"202609","sources":{"TAIEX":"https://openapi.twse.com.tw/v1/indicesReport/MI_5MINS_HIST + TWSE FMTQIK ALWAYS-CROSS-CHECK","TX":"https://openapi.taifex.com.tw/v1/DailyMarketReportFut + https://www.taifex.com.tw/cht/3/futDailyMarketExcel?commodity_id=TX ALWAYS-CROSS-CHECK"},"note":"Static same-day Market Pulse database. Runtime website makes no direct TWSE/TAIFEX API calls."});
function getMarketPulseData(){ return MARKET_DATA; }
